%{
/*
 * @Author: blueWALL-E
 * @Date: 2025-10-28 11:22:29
 * @LastEditTime: 2025-10-30 20:26:44
 * @FilePath: \GHV_open\GHV_analysis\L_analysis.m
 * @Description: 升力系数分析脚本
 * @Wearing:  Read only, do not modify place!!!
 * @Shortcut keys:  ctrl+alt+/ ctrl+alt+z
 */
%}
M_vals = linspace(4, 24, 50); % 马赫数范围，可按需要修改
ALPHA_vals = linspace(0, 12, 50); % 攻角范围(度)，可按需要修改
% 2. 固定给定条件 (你自己填实际值)
RE = 0; % 示例: 雷诺数或者某个代表量
LE = 0; % 示例: 另一边界层/长度相关量
% 上面这两个只是示意，请换成你题目里“给定的 LE 和 RE”
[M, ALPHA] = meshgrid(M_vals, ALPHA_vals);
CLbv = -8.19E-02 ...
    +4.70E-02 .* M ...
    +1.86E-02 .* ALPHA ...
    -4.73E-04 .* (ALPHA .* M) ...
    -9.19E-03 .* M .^ 2 ...
    -1.52E-04 .* ALPHA .^ 2 ...
    +5.99E-07 .* (ALPHA .* M) .^ 2 ...
    +7.74E-04 .* M .^ 3 ...
    +4.08E-06 .* ALPHA .^ 3 ...
    -2.93E-05 .* M .^ 4 ...
    -3.91E-07 .* ALPHA .^ 4 ...
    +4.12E-07 .* M .^ 5 ...
    +1.30E-08 .* ALPHA .^ 5;
CL_RE = -1.45E-05 ...
    +1.01E-04 .* ALPHA ...
    +7.10E-06 .* M ...
    -4.14E-04 .* RE ...
    -3.51E-06 .* (ALPHA .* RE) ...
    +4.70E-06 .* (ALPHA .* M) ...
    +8.72E-06 .* (M .* RE) ...
    -1.70E-07 .* (ALPHA .* M) * RE;
CL_LE = -1.45E-05 ...
    +1.01E-04 .* ALPHA ...
    +7.10E-06 .* M ...
    -4.14E-04 .* LE ...
    -3.51E-06 .* (ALPHA .* LE) ...
    +4.70E-06 .* (ALPHA .* M) ...
    +8.72E-06 .* (M .* LE) ...
    -1.70E-07 .* (ALPHA .* M) .* LE;
CL = CLbv + CL_RE + CL_LE;
% --- 三维曲面 ---
figure;
surf(M, ALPHA, CL); % 三维曲面
shading interp; % 平滑一下表面
colorbar; % 颜色条表示CL大小
xlabel('Mach Number M');
ylabel('\alpha (deg)');
zlabel('C_L');
title('C_L vs Mach & Angle of Attack');
grid on;
% --- 俯视等高线图 ---
figure;
contourf(M, ALPHA, CL, 30, 'LineColor', 'none'); % 30条等高线，填充颜色
colorbar;
xlabel('Mach Number M');
ylabel('\alpha (deg)');
title('C_L Contour Map (俯视等高线图)');
grid on;
% 选几个感兴趣的攻角（单位与你定义的 ALPHA 一致）
figure;
hold on; grid on;
alpha_list = 0:1:12; % 攻角范围
colors = jet(length(alpha_list)); % 蓝到红渐变

for i = 1:length(alpha_list)
    a = alpha_list(i);
    [~, idx] = min(abs(ALPHA_vals - a));
    plot(M_vals, CL(idx, :), 'Color', colors(i, :), ...
        'LineWidth', 2, ...
        'DisplayName', sprintf('\\alpha = %.1f°', a));
end

xlabel('Mach Number M');
ylabel('C_L');
title('C_L vs Mach at Different Angles of Attack');
legend('show', 'Location', 'eastoutside');
% ✅ 正确设置 colorbar
colormap(colors);
cbar = colorbar; % 获取 colorbar 句柄
cbar.Ticks = linspace(0, 1, length(alpha_list));
cbar.TickLabels = arrayfun(@(x) sprintf('%.0f°', x), alpha_list, 'UniformOutput', false);
ylabel(cbar, 'Angle of Attack (\alpha)', 'Rotation', 270); % 设置 colorbar 标签
